basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      responses: {}
  /v1/api/board:
    get:
      responses: {}
    post:
      responses: {}
  /v1/api/move/{column}/{row}:
    post:
      responses: {}
  /v1/api/move/passmove:
    post:
      responses: {}
  /v1/api/move/takeback/:
    post:
      responses: {}
schemes:
- http
swagger: "2.0"
