basePath: /
definitions:
  controller.album:
    properties:
      artistje:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Example API
  version: "1.0"
paths:
  /albums:
    get:
      responses: {}
      summary: Get all albums
      tags:
      - albums
    post:
      consumes:
      - application/json
      description: add by json account
      parameters:
      - description: Add Album
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/controller.album'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.album'
      summary: Post one album
      tags:
      - albums
  /albums/{id}:
    get:
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      summary: GET ER EENTJE
      tags:
      - albums
schemes:
- http
swagger: "2.0"
